"""Format 1 — a LaTeX résumé in the sb2nov / Abey George lineage.

The template somebody hands you when you ask a CS graduate what their CV looks
like, and it is popular for a reason: small-caps section headings under a rule,
job titles and dates on one ruled row, tight bullets, and a header of icon
links. It reads as deliberate rather than as a Word document that got away.

── Why this is a separate renderer ─────────────────────────────────────────

The other layouts in :mod:`aptly.export.templates` are a
:class:`~aptly.model.style.StyleProfile` — page, margins, three font specs,
rhythm — because that is all the .docx, .pdf and text writers need. This one is
not expressible that way. Its identity is in the *macros*: `\\resumeSubheading`
laying a title and a date on one `tabular*` row, `\\titleformat` putting a rule
under a small-caps heading, the `$\\sbullet$` certifications list. None of that
is a font size.

So Format 1 owns a LaTeX writer, and only a LaTeX writer. Choosing it and then
downloading .docx gives the profile's approximation of the look, which is
honest: we can match its typography in Word, not its macros.

── What was removed, and why ───────────────────────────────────────────────

The original preamble loads `fontawesome5` *and* `fontawesome`, `tikz`,
`marvosym`, `babel`, `multicol` and `glyphtounicode`, and pulls three icons in
as image files — `codeforces.jpg`, `leetcode.png`, `gfg.png`. Emitted as
written, this fails to compile for everyone: the images do not exist, and the
duplicate FontAwesome packages clash on a full TeX Live.

What is emitted keeps every macro and every visual decision, and drops what
cannot work: one FontAwesome package, no `tikz` (nothing drew with it), no
image icons — the coding-profile links are plain `\\href`s with the same
underline. It compiles on Overleaf and on a normal TeX Live without a single
file beside it, which is the difference between a deliverable and homework.
"""

from __future__ import annotations

from aptly.model.document import CVDocument, Entry, Section

#: Sections the template gives its "project" treatment — a bold underlined
#: title, the technologies beside it, a date on the right.
_PROJECTISH = {"projects", "publications"}

#: Sections it renders as a plain bulleted list rather than as entries.
_LISTISH = {"certifications", "awards", "languages", "interests"}


PREAMBLE = r"""%-------------------------
% Résumé in LaTeX
% Format 1 — generated by Aptly
% Lineage: https://github.com/sb2nov/resume, via Abey George
% License : MIT
%------------------------

\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage[usenames,dvipsnames]{color}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{tabularx}
\usepackage{fontawesome5}
\usepackage{graphicx}
\input{glyphtounicode}

\definecolor{cvblue}{HTML}{0E5484}
\definecolor{black}{HTML}{130810}
\definecolor{darkcolor}{HTML}{0F4539}
\definecolor{SlateGrey}{HTML}{2E2E2E}
\definecolor{LightGrey}{HTML}{666666}
\colorlet{heading}{darkcolor}
\colorlet{accent}{darkcolor}
\colorlet{emphasis}{SlateGrey}
\colorlet{body}{LightGrey}

%----------FONT OPTIONS----------
% Uncomment one. The default is Computer Modern.
% \usepackage[sfdefault]{FiraSans}
% \usepackage[sfdefault]{roboto}
% \usepackage[default]{sourcesanspro}
% \usepackage{CormorantGaramond}
% \usepackage{charter}

% Adjust margins
\addtolength{\oddsidemargin}{-0.6in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1.19in}
\addtolength{\topmargin}{-.7in}
\addtolength{\textheight}{1.4in}

\urlstyle{same}

\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

% Sections formatting
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large\bfseries
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

% Ensure the generated PDF is machine readable / ATS parsable
\pdfgentounicode=1

%-------------------------
% Custom commands
\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{1.0\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{\large#1} & \textbf{\small #2} \\
      \textit{\large#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubSubheading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \textit{\small#1} & \textit{\small #2} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{1.001\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & \textbf{\small #2}\\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}

\renewcommand\labelitemi{$\vcenter{\hbox{\tiny$\bullet$}}$}
\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.0in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

\newcommand\sbullet[1][.5]{\mathbin{\vcenter{\hbox{\scalebox{#1}{$\bullet$}}}}}

%-------------------------------------------
%%%%%%  RÉSUMÉ STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{document}
"""


_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def esc(text: str) -> str:
    """LaTeX-safe text.

    Backslash first, or the replacements this introduces get escaped again and
    a `&` becomes `\\textbackslash{}&`.
    """
    out = text.replace("\\", "\x00")
    for character, replacement in _ESCAPES.items():
        if character == "\\":
            continue
        out = out.replace(character, replacement)
    return out.replace("\x00", _ESCAPES["\\"])


def _url(link: str) -> str:
    return (
        link if link.startswith(("http://", "https://", "mailto:", "tel:")) else f"https://{link}"
    )


def _label(link: str) -> str:
    """What to call a link in the header.

    The template names the site rather than printing the URL — "Linkedin",
    "Github" — which is what keeps a header of five links to one line.
    """
    lowered = link.lower()
    for host, name in (
        ("linkedin", "LinkedIn"),
        ("github", "GitHub"),
        ("gitlab", "GitLab"),
        ("leetcode", "LeetCode"),
        ("codeforces", "Codeforces"),
        ("geeksforgeeks", "GeeksforGeeks"),
        ("kaggle", "Kaggle"),
        ("medium", "Medium"),
        ("behance", "Behance"),
        ("dribbble", "Dribbble"),
        ("stackoverflow", "Stack Overflow"),
    ):
        if host in lowered:
            return name
    return "Portfolio"


def _header(document: CVDocument) -> list[str]:
    contact = document.contact
    out = [r"%----------HEADING----------", r"\begin{center}"]

    name = contact.name or ""
    out.append(rf"    {{\Huge \scshape {esc(name)}}} \\ \vspace{{1pt}}")
    if contact.location:
        out.append(rf"    {esc(contact.location)} \\ \vspace{{1pt}}")

    # `\small` opens the row of icon links; each is an \href with the icon
    # raised onto the text baseline, exactly as the template does it.
    pieces: list[str] = []
    if contact.phone:
        pieces.append(
            rf"\href{{tel:{esc(contact.phone)}}}{{\raisebox{{-0.1\height}}\faPhone\ "
            rf"\underline{{{esc(contact.phone)}}}}}"
        )
    if contact.email:
        pieces.append(
            rf"\href{{mailto:{esc(contact.email)}}}{{\raisebox{{-0.2\height}}\faEnvelope\ "
            rf"\underline{{{esc(contact.email)}}}}}"
        )
    for link in contact.links:
        icon = {
            "LinkedIn": r"\faLinkedin",
            "GitHub": r"\faGithub",
            "GitLab": r"\faGitlab",
        }.get(_label(link), r"\faGlobe")
        pieces.append(
            rf"\href{{{_url(link)}}}{{\raisebox{{-0.2\height}}{icon}\ "
            rf"\underline{{{_label(link)}}}}}"
        )

    if pieces:
        out.append("    \\small " + " ~\n    ".join(pieces))

    out += [r"\end{center}", r" \vspace{0.5mm}", ""]
    return out


def _trim(text: str | None) -> str:
    """A parsed field, without the separator it was split on.

    "Senior Executive, Samsung SDS - December 2024" splits into a role and an
    org, and the org keeps the dash that preceded the dates. Harmless in a
    plain-text export where it reads as punctuation; in a ruled table cell it
    is a stray hyphen hanging in white space.
    """
    return (text or "").strip().strip("-–—·|,").strip()


def _entry(entry: Entry) -> list[str]:
    """One job or degree, as the template's four-cell heading."""
    title = _trim(entry.role)
    org = _trim(entry.org)
    dates = " -- ".join(part for part in (entry.start, entry.end) if part)
    where = _trim(entry.location)

    # The macro takes (title, dates, subtitle, location). An entry with an
    # employer puts it on the second row; one without leaves that row empty
    # rather than repeating the title into it.
    out = [
        r"    \resumeSubheading",
        rf"      {{{esc(title or org)}}}{{{esc(dates)}}}",
        rf"      {{{esc(org if title else '')}}}{{{esc(where)}}}",
    ]
    if entry.bullets:
        out.append(r"      \resumeItemListStart")
        out += [rf"        \resumeItem{{{esc(node.text)}}}" for node in entry.bullets]
        out.append(r"      \resumeItemListEnd")
    return out


def _project(entry: Entry) -> list[str]:
    name = _trim(entry.role) or _trim(entry.org)
    dates = " -- ".join(part for part in (entry.start, entry.end) if part)
    out = [
        r"     \resumeProjectHeading",
        rf"          {{\textbf{{\large{{\underline{{{esc(name)}}}}}}}}}{{{esc(dates)}}}\\",
    ]
    if entry.bullets:
        out.append(r"          \resumeItemListStart")
        out += [rf"            \resumeItem{{{esc(node.text)}}}" for node in entry.bullets]
        out.append(r"          \resumeItemListEnd")
        out.append(r"          \vspace{-13pt}")
    return out


def _section(section: Section) -> list[str]:
    title = (section.title or section.kind).upper()
    out = [rf"\section{{{esc(title)}}}"]

    # Certifications and the like: the template's $\sbullet$ list, one line
    # each, rather than the heavier entry machinery.
    if section.kind in _LISTISH:
        rows = [node.text for node in section.loose_nodes]
        rows += [
            " -- ".join(part for part in (entry.role, entry.org) if part)
            for entry in section.entries
        ]
        rows = [row for row in rows if row.strip()]
        if not rows:
            return []
        out += [rf"$\sbullet[.75] \hspace{{0.1cm}}$ {{{esc(row)}}} \\" for row in rows]
        out.append("")
        return out

    if section.kind == "skills":
        lines = [node.text for node in section.loose_nodes if node.text.strip()]
        if not lines:
            return []
        out += [
            r" \begin{itemize}[leftmargin=0.15in, label={}]",
            r"    \small{\item{",
        ]
        out += [rf"     {esc(line)} \\" for line in lines]
        out += [r"    }}", r" \end{itemize}", r" \vspace{-15pt}", ""]
        return out

    body: list[str] = []
    for node in section.loose_nodes:
        if node.text.strip():
            body.append(rf"    \resumeItem{{{esc(node.text)}}}")

    if section.kind in _PROJECTISH:
        out.append(r"    \vspace{-5pt}")
        out.append(r"    \resumeSubHeadingListStart")
        for entry in section.entries:
            out += _project(entry)
        out += body
        out.append(r"    \resumeSubHeadingListEnd")
        out.append("")
        return out

    if not section.entries and body:
        # A summary or a freeform block: printed as prose, since the template
        # has no macro for it and a bulleted single paragraph reads as a stub.
        out += [esc(node.text) for node in section.loose_nodes if node.text.strip()]
        out.append("")
        return out

    out.append(r"  \resumeSubHeadingListStart")
    for entry in section.entries:
        out += _entry(entry)
    out += body
    out.append(r"  \resumeSubHeadingListEnd")
    out.append(r"\vspace{-12pt}")
    out.append("")
    return out


def render_format1(document: CVDocument) -> str:
    """The whole document, in Format 1."""
    out = [PREAMBLE]
    out += _header(document)

    for section in document.sections:
        if section.kind == "header":
            continue
        if not section.nodes:
            continue
        out += _section(section)

    out.append(r"\end{document}")
    return "\n".join(out) + "\n"


__all__ = ["PREAMBLE", "esc", "render_format1"]
