/**
 * Scoring the CV against the job, in the browser, on every keystroke.
 *
 * This is a deliberate second implementation of `analyse/scoring.py`. It exists
 * because the match figure has to move *while* somebody edits — a number that
 * only updates on a round trip is a number nobody connects to what they just
 * did — and a server call per keystroke is neither fast enough nor affordable.
 *
 * Two implementations of one rule can drift, so the split is drawn to make that
 * as hard as possible:
 *
 * - **The server does all the thinking.** Which terms are worth looking for,
 *   whether a phrase is a product name or a description, and what a term's
 *   aliases are — all decided once, server-side, and shipped resolved. Nothing
 *   here knows that "K8s" means "Kubernetes".
 * - **This file only looks things up.** Two rules, below: fold the text, then
 *   whole-token match. That is the entire contract.
 *
 * `score.contract.json` is generated by the Python tests and replayed against
 * this code by `score.test.ts`, so a change on either side that breaks the
 * agreement fails a test rather than quietly showing two different numbers.
 */

export type GapStatus = "covered" | "partial" | "missing";

export interface TermGroup {
  label: string;
  /** Already lowercased and folded by the server. */
  aliases: string[];
}

export interface LiveRule {
  id: string;
  requirement: string;
  essential: boolean;
  /** Empty when this requirement is judged rather than named. */
  terms: TermGroup[];
  combine: "any" | "all";
  /** The frozen verdict for a judged requirement. */
  fixed: GapStatus | null;
}

export interface ScoreCard {
  rules: LiveRule[];
  /** What the CV scored on arrival, so the UI can show movement, not just a number. */
  baseline: number;
  /** False when this is a literal-only reading — it changes what the score means. */
  semantic: boolean;
}

export interface RuleResult {
  id: string;
  requirement: string;
  essential: boolean;
  status: GapStatus;
  present: string[];
  absent: string[];
}

export interface ScoreResult {
  score: number;
  baseline: number;
  results: RuleResult[];
}

/* ── Rule 1: folding ─────────────────────────────────────────────────────── */

/**
 * Mirrors `terms.canonical`.
 *
 * `+`, `#`, `.`, `-`, `/` and `_` survive: dropping them turns C++ into C, C#
 * into C, .NET into net and scikit-learn into two words. Everything else
 * becomes a space, and runs of space collapse.
 */
export function canonical(text: string): string {
  return text
    .normalize("NFKC")
    .toLowerCase()
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[–—]/g, "-")
    .replace(/[^\w+#./\s-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/* ── Rule 2: whole-token matching ────────────────────────────────────────── */

const patterns = new Map<string, RegExp>();

/**
 * Mirrors `terms._pattern`.
 *
 * The token boundary is "not a letter or a digit", which is what stops `sql`
 * matching inside `nosql` and `java` inside `javascript` while still finding
 * `c++` in "C++ and Java". Those are different skills, and a substring search
 * calls all of them present.
 */
function pattern(alias: string): RegExp {
  const cached = patterns.get(alias);
  if (cached) return cached;

  const body = alias
    .split(/\s+/)
    .map((word) => word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
    .join("\\s+");
  const built = new RegExp(`(?<![A-Za-z0-9])${body}(?![A-Za-z0-9])`);

  patterns.set(alias, built);
  return built;
}

/** Mirrors `terms.names_any`. `haystack` must already be canonical. */
export function namesAny(haystack: string, aliases: string[]): boolean {
  return aliases.some((alias) => alias.length > 0 && pattern(alias).test(haystack));
}

/* ── Scoring ─────────────────────────────────────────────────────────────── */

function statusFrom(rule: LiveRule, hits: number): GapStatus {
  if (rule.terms.length === 0) return rule.fixed ?? "missing";
  if (hits === 0) return "missing";
  if (rule.combine === "any" || hits === rule.terms.length) return "covered";
  return "partial";
}

/**
 * Score the CV's current text. Mirrors `scoring.evaluate`.
 *
 * Partial counts half, exactly as the server does, so the figure somebody
 * watches while editing is on the same scale as the one they are given on
 * approval. Two numbers that mean almost the same thing is worse than one — the
 * score would visibly jump at the end and read as invented.
 */
export function evaluate(card: ScoreCard, text: string): ScoreResult {
  const haystack = canonical(text);

  const results: RuleResult[] = card.rules.map((rule) => {
    const present: string[] = [];
    const absent: string[] = [];
    for (const group of rule.terms) {
      (namesAny(haystack, group.aliases) ? present : absent).push(group.label);
    }
    return {
      id: rule.id,
      requirement: rule.requirement,
      essential: rule.essential,
      status: statusFrom(rule, present.length),
      present,
      absent,
    };
  });

  if (results.length === 0) {
    return { score: 0, baseline: card.baseline, results: [] };
  }

  // Weighted exactly as the server weights it. A job post states a handful of
  // conditions and then lists a dozen things it would like; counting them
  // equally is how a CV that meets every stated requirement and half the wishes
  // scores in the fifties, which is not what any recruiter reading it would say.
  const weight = (essential: boolean) => (essential ? 1 : 0.34);
  const credit = (status: GapStatus) =>
    status === "covered" ? 1 : status === "partial" ? 0.5 : 0;

  const earned = results.reduce(
    (total, item) => total + weight(item.essential) * credit(item.status),
    0,
  );
  const possible = results.reduce((total, item) => total + weight(item.essential), 0);

  return {
    // Half-up, matching `analyse/percent.py`. JavaScript's Math.round is
    // already half-up; Python's round is not, which is why that module exists.
    score: possible <= 0 ? 0 : Math.floor((100 * earned) / possible + 0.5),
    baseline: card.baseline,
    results,
  };
}
